defalut:
  defalut:
    - XVIDEOS まとめ（仮）| XVIDEOSをより快適に楽しむためのキュレーションサービス

top:
  index:
    - XVIDEOS まとめ（仮）| XVIDEOSをより快適に楽しむためのキュレーションサービス

detail:
  index:
    - %s | XVIDEOS まとめ（仮）

search:
  index:
    - [%s]の検索結果 | XVIDEOS まとめ（仮）

create:
  index:
    - 新規作成 | XVIDEOSをより快適に楽しむためのキュレーションサービス正