defalut:
  defalut:
    - XVIDEOS まとめ（仮）| XVIDEOSをより快適に楽しむためのキュレーションサービス
    - XVIDEOS まとめ（仮）はXVIDEOSの快適に閲覧したい紳士のためのまとめサービスです。PC、スマートフォン（iPhone、Android）に対応。好みのジャンルのエロ動画がすぐに見つかります。
    - エロ動画、XVIDEOS、まとめ、えろ、エロ、無修正

top:
  index:
    - XVIDEOS まとめ（仮）| XVIDEOSをより快適に楽しむためのキュレーションサービス
    - XVIDEOS まとめ（仮）はXVIDEOSの快適に閲覧したい紳士のためのまとめサービスです。PC、スマートフォン（iPhone、Android）に対応。好みのジャンルのエロ動画がすぐに見つかります。
    - エロ動画、XVIDEOS、まとめ、えろ、エロ、無修正

detail:
  index:
    - %s | XVIDEOS まとめ（仮）
    -
    - エロ動画、XVIDEOS、まとめ、えろ、エロ、無修正

search:
  index:
    - [%s]の検索結果 | XVIDEOS まとめ（仮）
    - XVIDEOSをより快適に楽しむためのキュレーションサービス
    - エロ動画、XVIDEOS、まとめ、えろ、エロ、無修正

create:
  index:
    - 新規作成 | XVIDEOSをより快適に楽しむためのキュレーションサービス
    - XVIDEOS まとめ（仮）はXVIDEOSの快適に閲覧したい紳士のためのまとめサービスです。PC、スマートフォン（iPhone、Android）に対応。好みのジャンルのエロ動画がすぐに見つかります。
    - エロ動画、XVIDEOS、まとめ、えろ、エロ、無修正